/* Generated By:JavaCC: Do not edit this line. CIM_PrepConstants.java */
package org.wbemservices.wbem.compiler.prep;

public interface CIM_PrepConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 1;
  int MULTI_LINE_COMMENT = 2;
  int CHAR = 3;
  int PRE_PRAGMA = 4;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<CHAR>",
    "<PRE_PRAGMA>",
  };

}
