/* Generated By:JavaCC: Do not edit this line. CIM_MofcTokenManager.java */
package org.wbemservices.wbem.compiler.mofc;

public class CIM_MofcTokenManager implements CIM_MofcConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 2;
         return jjMoveNfa_0(2, 0);
      case 10:
         jjmatchedKind = 4;
         return jjMoveNfa_0(2, 0);
      case 13:
         jjmatchedKind = 3;
         return jjMoveNfa_0(2, 0);
      case 32:
         jjmatchedKind = 1;
         return jjMoveNfa_0(2, 0);
      case 40:
         jjmatchedKind = 74;
         return jjMoveNfa_0(2, 0);
      case 41:
         jjmatchedKind = 75;
         return jjMoveNfa_0(2, 0);
      case 44:
         jjmatchedKind = 66;
         return jjMoveNfa_0(2, 0);
      case 58:
         jjmatchedKind = 67;
         return jjMoveNfa_0(2, 0);
      case 59:
         jjmatchedKind = 68;
         return jjMoveNfa_0(2, 0);
      case 61:
         jjmatchedKind = 69;
         return jjMoveNfa_0(2, 0);
      case 65:
         return jjMoveStringLiteralDfa1_0(0x11040000L);
      case 66:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L);
      case 67:
         return jjMoveStringLiteralDfa1_0(0x800000020000L);
      case 68:
         return jjMoveStringLiteralDfa1_0(0x4000200000000L);
      case 69:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 70:
         return jjMoveStringLiteralDfa1_0(0x10000080000000L);
      case 73:
         return jjMoveStringLiteralDfa1_0(0x4091000L);
      case 76:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 77:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 78:
         return jjMoveStringLiteralDfa1_0(0x20000000008400L);
      case 79:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 80:
         return jjMoveStringLiteralDfa1_0(0x900000L);
      case 81:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 82:
         return jjMoveStringLiteralDfa1_0(0x600802200000L);
      case 83:
         return jjMoveStringLiteralDfa1_0(0x1154040002800L);
      case 84:
         return jjMoveStringLiteralDfa1_0(0x8001400000000L);
      case 85:
         return jjMoveStringLiteralDfa1_0(0xaa000000000L);
      case 91:
         jjmatchedKind = 72;
         return jjMoveNfa_0(2, 0);
      case 93:
         jjmatchedKind = 73;
         return jjMoveNfa_0(2, 0);
      case 97:
         return jjMoveStringLiteralDfa1_0(0x11040000L);
      case 98:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L);
      case 99:
         return jjMoveStringLiteralDfa1_0(0x800000020000L);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x4000200000000L);
      case 101:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x10000080000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x4091000L);
      case 108:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 109:
         return jjMoveStringLiteralDfa1_0(0x400000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x20000000008400L);
      case 111:
         return jjMoveStringLiteralDfa1_0(0x8000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x900000L);
      case 113:
         return jjMoveStringLiteralDfa1_0(0x20000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x600802200000L);
      case 115:
         return jjMoveStringLiteralDfa1_0(0x1154040002800L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x8001400000000L);
      case 117:
         return jjMoveStringLiteralDfa1_0(0xaa000000000L);
      case 123:
         jjmatchedKind = 70;
         return jjMoveNfa_0(2, 0);
      case 125:
         jjmatchedKind = 71;
         return jjMoveNfa_0(2, 0);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 0);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa2_0(active0, 0x14000000800400L);
      case 67:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000800L);
      case 69:
         return jjMoveStringLiteralDfa2_0(active0, 0x600802600000L);
      case 70:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 1;
         }
         break;
      case 72:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L);
      case 73:
         return jjMoveStringLiteralDfa2_0(active0, 0x1fe200000000L);
      case 76:
         return jjMoveStringLiteralDfa2_0(active0, 0x80020000L);
      case 78:
         return jjMoveStringLiteralDfa2_0(active0, 0x105091000L);
      case 79:
         return jjMoveStringLiteralDfa2_0(active0, 0x200040000e000L);
      case 82:
         return jjMoveStringLiteralDfa2_0(active0, 0x8001000100000L);
      case 83:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
      case 85:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000020000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x14000000800400L);
      case 99:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000800L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x600802600000L);
      case 102:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 1;
         }
         break;
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x800000000000L);
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1fe200000000L);
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x80020000L);
      case 110:
         return jjMoveStringLiteralDfa2_0(active0, 0x105091000L);
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x200040000e000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x8001000100000L);
      case 115:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x40000L);
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000020000000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 1);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 1);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa3_0(active0, 0xe011a0020000L);
      case 67:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000L);
      case 68:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 70:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 72:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 76:
         return jjMoveStringLiteralDfa3_0(active0, 0x30000000000000L);
      case 77:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 78:
         return jjMoveStringLiteralDfa3_0(active0, 0x1fe000008000L);
      case 79:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000040100000L);
      case 82:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000800000L);
      case 83:
         return jjMoveStringLiteralDfa3_0(active0, 0xe04050000L);
      case 84:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000400000L);
      case 85:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000002000L);
      case 89:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0xe011a0020000L);
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x5000L);
      case 100:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L);
      case 102:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x200000L);
      case 104:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x30000000000000L);
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0x400L);
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x1fe000008000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000040100000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x1000000800000L);
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0xe04050000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x4000000400000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x8000000002000L);
      case 121:
         if ((active0 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 24;
            jjmatchedPos = 2;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(2, 2);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 2);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa4_0(active0, 0x200804000L);
      case 66:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 69:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000200c00L);
      case 72:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 73:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000080000L);
      case 76:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2600020009000L);
      case 78:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 79:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 80:
         return jjMoveStringLiteralDfa4_0(active0, 0x40100000L);
      case 82:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000002000L);
      case 83:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000020000L);
      case 84:
         return jjMoveStringLiteralDfa4_0(active0, 0x1fe804010000L);
      case 85:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 86:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x200804000L);
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      case 101:
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000200c00L);
      case 104:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000080000L);
      case 108:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x2600020009000L);
      case 110:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x40100000L);
      case 114:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000002000L);
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000020000L);
      case 116:
         return jjMoveStringLiteralDfa4_0(active0, 0x1fe804010000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000L);
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 3);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 3);
   }
   switch(curChar)
   {
      case 49:
         return jjMoveStringLiteralDfa5_0(active0, 0x818000000000L);
      case 51:
         return jjMoveStringLiteralDfa5_0(active0, 0x260000000000L);
      case 54:
         return jjMoveStringLiteralDfa5_0(active0, 0x580000000000L);
      case 56:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 4;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa5_0(active0, 0x4010000L);
      case 66:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000000L);
      case 67:
         return jjMoveStringLiteralDfa5_0(active0, 0xc2000L);
      case 69:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000100000L);
      case 73:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 76:
         return jjMoveStringLiteralDfa5_0(active0, 0x100004000L);
      case 77:
         return jjMoveStringLiteralDfa5_0(active0, 0x800800L);
      case 78:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L);
      case 79:
         return jjMoveStringLiteralDfa5_0(active0, 0x80408000L);
      case 82:
         return jjMoveStringLiteralDfa5_0(active0, 0x800200000L);
      case 83:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000400L);
      case 84:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L);
      case 85:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x4010000L);
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x600000000L);
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0xc2000L);
      case 101:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x2000000100000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L);
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x100004000L);
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x800800L);
      case 110:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000000000L);
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x80408000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x800200000L);
      case 115:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_0(active0, 0x1000000400L);
      case 116:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L);
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 4);
}
private final int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 4);
   }
   switch(curChar)
   {
      case 50:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 5;
         }
         break;
      case 52:
         if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 5;
         }
         break;
      case 54:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
         }
         break;
      case 65:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000080000L);
      case 67:
         return jjMoveStringLiteralDfa6_0(active0, 0x400008000L);
      case 68:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 69:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x100a00000L);
      case 70:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 71:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 5;
         }
         break;
      case 73:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000800040000L);
      case 76:
         return jjMoveStringLiteralDfa6_0(active0, 0x1200000000L);
      case 78:
         return jjMoveStringLiteralDfa6_0(active0, 0x4010000L);
      case 80:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 82:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 97:
         if ((active0 & 0x800L) != 0L)
         {
            jjmatchedKind = 11;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x2000000080000L);
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x400008000L);
      case 100:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x1000L);
      case 101:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x100a00000L);
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000L);
      case 103:
         if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 5;
         }
         break;
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000800040000L);
      case 108:
         return jjMoveStringLiteralDfa6_0(active0, 0x1200000000L);
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x4010000L);
      case 112:
         return jjMoveStringLiteralDfa6_0(active0, 0x400L);
      case 114:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 5);
}
private final int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 5);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000048400L);
      case 67:
         return jjMoveStringLiteralDfa7_0(active0, 0x804010000L);
      case 69:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L);
      case 73:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      case 76:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 77:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L);
      case 78:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 79:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 84:
         return jjMoveStringLiteralDfa7_0(active0, 0x980000L);
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000048400L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x804010000L);
      case 101:
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 12;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200000000L);
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000L);
      case 108:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000L);
      case 109:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000000000L);
      case 110:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000L);
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x980000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 6);
}
private final int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 6);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L);
      case 67:
         return jjMoveStringLiteralDfa8_0(active0, 0x200400L);
      case 69:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x20810000L);
      case 73:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 76:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 79:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      case 84:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800040000L);
      case 86:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 89:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 7;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000000L);
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x200400L);
      case 101:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 7;
         }
         return jjMoveStringLiteralDfa8_0(active0, 0x20810000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x80000L);
      case 108:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0x200000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x1800040000L);
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000L);
      case 121:
         if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 7;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(2, 7);
}
private final int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 7);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 7);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000L);
      case 69:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x900000000L);
      case 73:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000L);
      case 76:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 79:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 82:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 8;
         }
         break;
      case 83:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000L);
      case 86:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L);
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0x1000000000L);
      case 101:
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 8;
         }
         return jjMoveStringLiteralDfa9_0(active0, 0x900000000L);
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x40000L);
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x80000L);
      case 114:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 8;
         }
         else if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 8;
         }
         break;
      case 115:
         return jjMoveStringLiteralDfa9_0(active0, 0x400000000L);
      case 118:
         return jjMoveStringLiteralDfa9_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 8);
}
private final int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 8);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 8);
   }
   switch(curChar)
   {
      case 66:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L);
      case 68:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L);
      case 78:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 9;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa10_0(active0, 0x50000L);
      case 82:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 83:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 9;
         }
         break;
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0x1000000000L);
      case 100:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 9;
         }
         break;
      case 101:
         return jjMoveStringLiteralDfa10_0(active0, 0x200000000L);
      case 110:
         if ((active0 & 0x80000L) != 0L)
         {
            jjmatchedKind = 19;
            jjmatchedPos = 9;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x50000L);
      case 114:
         return jjMoveStringLiteralDfa10_0(active0, 0x100000000L);
      case 115:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 9;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(2, 9);
}
private final int jjMoveStringLiteralDfa10_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 9);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 9);
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000L);
      case 76:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000L);
      case 78:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 10;
         }
         break;
      case 82:
         return jjMoveStringLiteralDfa11_0(active0, 0x300000000L);
      case 99:
         return jjMoveStringLiteralDfa11_0(active0, 0x10000L);
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0x1000000000L);
      case 110:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 10;
         }
         break;
      case 114:
         return jjMoveStringLiteralDfa11_0(active0, 0x300000000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 10);
}
private final int jjMoveStringLiteralDfa11_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 10);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 10);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000L);
      case 69:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 11;
         }
         break;
      case 73:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000L);
      case 82:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000000L);
      case 97:
         return jjMoveStringLiteralDfa12_0(active0, 0x10000L);
      case 101:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 11;
         }
         break;
      case 105:
         return jjMoveStringLiteralDfa12_0(active0, 0x100000000L);
      case 114:
         return jjMoveStringLiteralDfa12_0(active0, 0x200000000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 11);
}
private final int jjMoveStringLiteralDfa12_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 11);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 11);
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000L);
      case 73:
         return jjMoveStringLiteralDfa13_0(active0, 0x200000000L);
      case 76:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000L);
      case 100:
         return jjMoveStringLiteralDfa13_0(active0, 0x100000000L);
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x200000000L);
      case 108:
         return jjMoveStringLiteralDfa13_0(active0, 0x10000L);
      default :
         break;
   }
   return jjMoveNfa_0(2, 12);
}
private final int jjMoveStringLiteralDfa13_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 12);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 12);
   }
   switch(curChar)
   {
      case 68:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000000L);
      case 69:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 13;
         }
         else if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 13;
         }
         break;
      case 100:
         return jjMoveStringLiteralDfa14_0(active0, 0x200000000L);
      case 101:
         if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 13;
         }
         else if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 13;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(2, 13);
}
private final int jjMoveStringLiteralDfa14_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(2, 13);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(2, 13);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 14;
         }
         break;
      case 101:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 14;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(2, 14);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 75;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  else if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(0, 5);
                  else if (curChar == 35)
                     jjAddStates(6, 8);
                  else if (curChar == 47)
                     jjAddStates(9, 10);
                  else if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 27;
                  else if (curChar == 39)
                     jjAddStates(11, 12);
                  else if (curChar == 34)
                     jjCheckNAddStates(13, 15);
                  else if (curChar == 46)
                     jjCheckNAdd(10);
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     jjCheckNAdd(4);
                  }
                  else if (curChar == 48)
                  {
                     if (kind > 58)
                        kind = 58;
                     jjCheckNAddTwoStates(69, 72);
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 6;
                  else if (curChar == 43)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(0, 1);
                  break;
               case 0:
                  if ((0x3000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(0, 1);
                  break;
               case 3:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(4);
                  break;
               case 4:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  jjCheckNAdd(4);
                  break;
               case 5:
                  if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 6:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(7);
                  break;
               case 7:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 57)
                     kind = 57;
                  jjCheckNAdd(7);
                  break;
               case 8:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(8, 9);
                  break;
               case 9:
                  if (curChar == 46)
                     jjCheckNAdd(10);
                  break;
               case 10:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAddTwoStates(10, 11);
                  break;
               case 12:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(13);
                  break;
               case 13:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 60)
                     kind = 60;
                  jjCheckNAdd(13);
                  break;
               case 14:
                  if (curChar == 34)
                     jjCheckNAddStates(13, 15);
                  break;
               case 15:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 17:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 18:
                  if (curChar == 34 && kind > 61)
                     kind = 61;
                  break;
               case 19:
                  if (curChar == 39)
                     jjAddStates(11, 12);
                  break;
               case 20:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 21:
                  if (curChar == 39 && kind > 62)
                     kind = 62;
                  break;
               case 23:
                  if ((0x8400000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 25:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 26:
                  if (curChar == 36)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 29:
                  if (curChar == 47)
                     jjAddStates(9, 10);
                  break;
               case 30:
                  if (curChar == 47)
                     jjCheckNAddStates(16, 18);
                  break;
               case 31:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(16, 18);
                  break;
               case 32:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 33:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 34:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 36:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 37:
                  if (curChar == 42)
                     jjCheckNAddStates(19, 21);
                  break;
               case 38:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(39, 37);
                  break;
               case 39:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(39, 37);
                  break;
               case 40:
                  if (curChar == 47 && kind > 6)
                     kind = 6;
                  break;
               case 41:
                  if (curChar == 35)
                     jjAddStates(6, 8);
                  break;
               case 43:
                  if ((0x100002600L & l) != 0L && kind > 7)
                     kind = 7;
                  break;
               case 44:
                  if (curChar == 10 && kind > 7)
                     kind = 7;
                  break;
               case 45:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 44;
                  break;
               case 49:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 51:
                  if ((0x100002600L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 52:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 53:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 52;
                  break;
               case 57:
                  if (curChar == 35)
                     jjstateSet[jjnewStateCnt++] = 56;
                  break;
               case 59:
                  if ((0x100002600L & l) != 0L && kind > 9)
                     kind = 9;
                  break;
               case 60:
                  if (curChar == 10 && kind > 9)
                     kind = 9;
                  break;
               case 61:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 60;
                  break;
               case 67:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(0, 5);
                  break;
               case 68:
                  if (curChar == 48)
                     jjCheckNAdd(69);
                  break;
               case 69:
                  if ((0xff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  jjCheckNAdd(69);
                  break;
               case 70:
                  if (curChar == 48 && kind > 58)
                     kind = 58;
                  break;
               case 71:
                  if (curChar == 48)
                     jjCheckNAdd(72);
                  break;
               case 73:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjstateSet[jjnewStateCnt++] = 73;
                  break;
               case 74:
                  if (curChar != 48)
                     break;
                  if (kind > 58)
                     kind = 58;
                  jjCheckNAddTwoStates(69, 72);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 25:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(25);
                  break;
               case 1:
                  if ((0x400000004L & l) != 0L && kind > 54)
                     kind = 54;
                  break;
               case 11:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(22, 23);
                  break;
               case 15:
                  jjCheckNAddStates(13, 15);
                  break;
               case 16:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 17:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAddStates(13, 15);
                  break;
               case 20:
                  if ((0xffffffffefffffffL & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 22:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 23:
                  if ((0x14404410000000L & l) != 0L)
                     jjCheckNAdd(21);
                  break;
               case 27:
               case 28:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 64)
                     kind = 64;
                  jjCheckNAdd(28);
                  break;
               case 31:
                  jjAddStates(16, 18);
                  break;
               case 36:
                  jjCheckNAddTwoStates(36, 37);
                  break;
               case 38:
               case 39:
                  jjCheckNAddTwoStates(39, 37);
                  break;
               case 42:
                  if (curChar == 69)
                     jjAddStates(24, 25);
                  break;
               case 46:
                  if (curChar == 78)
                     jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 47:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 46;
                  break;
               case 48:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 47;
                  break;
               case 50:
                  if (curChar == 69)
                     jjAddStates(26, 27);
                  break;
               case 54:
                  if (curChar == 76)
                     jjstateSet[jjnewStateCnt++] = 50;
                  break;
               case 55:
                  if (curChar == 73)
                     jjstateSet[jjnewStateCnt++] = 54;
                  break;
               case 56:
                  if (curChar == 70)
                     jjstateSet[jjnewStateCnt++] = 55;
                  break;
               case 58:
                  if ((0x200000002L & l) != 0L)
                     jjAddStates(28, 29);
                  break;
               case 62:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 58;
                  break;
               case 63:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 62;
                  break;
               case 64:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 63;
                  break;
               case 65:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 64;
                  break;
               case 66:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 65;
                  break;
               case 72:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(73);
                  break;
               case 73:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  jjCheckNAdd(73);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 15:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(13, 15);
                  break;
               case 20:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 31:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjAddStates(16, 18);
                  break;
               case 36:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(36, 37);
                  break;
               case 38:
               case 39:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     jjCheckNAddTwoStates(39, 37);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 75 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
static final int[] jjnextStates = {
   0, 68, 70, 71, 8, 9, 49, 57, 66, 30, 35, 20, 22, 15, 16, 18, 
   31, 32, 34, 37, 38, 40, 12, 13, 43, 45, 51, 53, 59, 61, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default : 
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, "\54", "\72", 
"\73", "\75", "\173", "\175", "\133", "\135", "\50", "\51", };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xffffffffffffff81L, 0xffdL, 
};
static final long[] jjtoSkip = {
   0x7eL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x60L, 0x0L, 
};
private JavaCharStream input_stream;
private final int[] jjrounds = new int[75];
private final int[] jjstateSet = new int[150];
protected char curChar;
public CIM_MofcTokenManager(JavaCharStream stream)
{
   if (JavaCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public CIM_MofcTokenManager(JavaCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(JavaCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 75; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(JavaCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

private final Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public final Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

}
