/* Generated By:JavaCC: Do not edit this line. CIM_MofcConstants.java */
package org.wbemservices.wbem.compiler.mofc;

public interface CIM_MofcConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int MULTI_LINE_COMMENT = 6;
  int PRECOMP_LINE = 7;
  int PRECOMP_FILE = 8;
  int PRAGMA = 9;
  int NAMESPACE = 10;
  int SCHEMA = 11;
  int INCLUDE = 12;
  int SOURCE = 13;
  int LOCALE = 14;
  int NONLOCALE = 15;
  int INSTANCELOCALE = 16;
  int CLASS = 17;
  int ASSOCIATION = 18;
  int INDICATION = 19;
  int PROPERTY = 20;
  int REFERENCE = 21;
  int METHOD = 22;
  int PARAMETER = 23;
  int ANY = 24;
  int REF = 25;
  int INSTANCE = 26;
  int OF = 27;
  int AS = 28;
  int QUALIFIER = 29;
  int SCOPE = 30;
  int FLAVOR = 31;
  int ENABLEOVERRIDE = 32;
  int DISABLEOVERRIDE = 33;
  int TOSUBCLASS = 34;
  int RESTRICTED = 35;
  int TRANSLATABLE = 36;
  int DT_UINT8 = 37;
  int DT_SINT8 = 38;
  int DT_UINT16 = 39;
  int DT_SINT16 = 40;
  int DT_UINT32 = 41;
  int DT_SINT32 = 42;
  int DT_UINT64 = 43;
  int DT_SINT64 = 44;
  int DT_REAL32 = 45;
  int DT_REAL64 = 46;
  int DT_CHAR16 = 47;
  int DT_STR = 48;
  int DT_BOOL = 49;
  int DT_DATETIME = 50;
  int TRUE_VALUE = 51;
  int FALSE_VALUE = 52;
  int NULL_VALUE = 53;
  int BINARY_VALUE = 54;
  int OCTAL_VALUE = 55;
  int POS_DECIMAL_VALUE = 56;
  int NEG_DECIMAL_VALUE = 57;
  int ZERO = 58;
  int HEX_VALUE = 59;
  int REAL_VALUE = 60;
  int STRING_VALUE = 61;
  int CHAR_VALUE = 62;
  int IDENTIFIER = 63;
  int ALIAS_IDENTIFIER = 64;
  int IDENT_CHAR = 65;
  int COMMA = 66;
  int COLON = 67;
  int SEMICOLON = 68;
  int EQUAL = 69;
  int OPEN_CUR_BRA = 70;
  int CLOSE_CUR_BRA = 71;
  int OPEN_SQU_BRA = 72;
  int CLOSE_SQU_BRA = 73;
  int OPEN_BRA = 74;
  int CLOSE_BRA = 75;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<PRECOMP_LINE>",
    "<PRECOMP_FILE>",
    "<PRAGMA>",
    "\"namespace\"",
    "\"schema\"",
    "\"include\"",
    "\"source\"",
    "\"locale\"",
    "\"nonlocale\"",
    "\"instancelocale\"",
    "\"class\"",
    "\"association\"",
    "\"indication\"",
    "\"property\"",
    "\"reference\"",
    "\"method\"",
    "\"parameter\"",
    "\"any\"",
    "\"ref\"",
    "\"instance\"",
    "\"of\"",
    "\"as\"",
    "\"qualifier\"",
    "\"scope\"",
    "\"flavor\"",
    "\"enableoverride\"",
    "\"disableoverride\"",
    "\"tosubclass\"",
    "\"restricted\"",
    "\"translatable\"",
    "\"uint8\"",
    "\"sint8\"",
    "\"uint16\"",
    "\"sint16\"",
    "\"uint32\"",
    "\"sint32\"",
    "\"uint64\"",
    "\"sint64\"",
    "\"real32\"",
    "\"real64\"",
    "\"char16\"",
    "\"string\"",
    "\"boolean\"",
    "\"datetime\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<BINARY_VALUE>",
    "<OCTAL_VALUE>",
    "<POS_DECIMAL_VALUE>",
    "<NEG_DECIMAL_VALUE>",
    "<ZERO>",
    "<HEX_VALUE>",
    "<REAL_VALUE>",
    "<STRING_VALUE>",
    "<CHAR_VALUE>",
    "<IDENTIFIER>",
    "<ALIAS_IDENTIFIER>",
    "<IDENT_CHAR>",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"=\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
